//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        public int Med_ID { get; set; }
        public string Name { get; set; }
        public int Quantity { get; set; }
        public double Price { get; set; }
        public System.DateTime Expire_Date { get; set; }
        public int ChemicalForm { get; set; }
        public int Company_ID { get; set; }
    
        public virtual ChemicalForm ChemicalForm1 { get; set; }
        public virtual Company Company { get; set; }
    }
}
