//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Phar_id { get; set; }
        public double Price { get; set; }
        public int Quantity { get; set; }
        public Nullable<bool> create { get; set; }
        public Nullable<bool> Delete { get; set; }
        public Nullable<bool> Edit { get; set; }
        public Nullable<bool> Demand { get; set; }
    }
}
