//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class xmlphar
    {
        public int id { get; set; }
        public int Phar_id_sending { get; set; }
        public int Phar_id_receiving { get; set; }
        public string text { get; set; }
    
        public virtual pharmacy pharmacy { get; set; }
        public virtual pharmacy pharmacy1 { get; set; }
    }
}
