//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_9ff70c_centralEntities : DbContext
    {
        public db_9ff70c_centralEntities()
            : base("name=db_9ff70c_centralEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<demand> demands { get; set; }
        public DbSet<med> meds { get; set; }
        public DbSet<pharmacy> pharmacies { get; set; }
        public DbSet<warehouse> warehouses { get; set; }
        public DbSet<warehousemedicine> warehousemedicines { get; set; }
    }
}
